### ISSUE TITLE
Create Container and Child Elements for Accordion

### ISSUE THREAD

**Issue by frastlin** [WhatSock/bootstrap-react#11]
Hello,
This extends:
https://github.com/WhatSock/bootstrap-react/issues/3

I would like to convert Accordion to be wrapped in a JSX tag like:

    <Accordion title="test1">This is test content within the accordion</Accordion>

I see that there are a lot of unique ids that need to be generated. This can be done by appending:

    new Date().getUTCMilliseconds()

to the end of any component.

I also see that the default behavior for the Accordion is to be:

Expanded button
Collapsed button
Collapsed button
Content

The above proposed syntax would yield:

Expanded button
Content
Collapsed button
Collapsed button

I think the best solution for this would be creating an AccordionGroup. The syntax would be:

	<AccordionGroup>
		<Accordion title="test1">Some content</Accordion>
		<Accordion title="Test2">Some content</Accordion>
	</AccordionGroup>

What do you think?
I will send a PR in a little bit.

**Comment by frastlin** [comment]
Actually, I just viewed the behavior of accordion and it is one region for one item. If we want to make a group element, it's totally possible, but I'll do a PR with the first behavior.

**Comment by frastlin** [comment]
It looks like the data-accordiongroup does require some extra group attributes, and doesn't just work when you give two separate renderings with the same group name.
This means I will go ahead and create an AccordionGroup component.

**Comment by frastlin** [comment]
OK, the component is:
https://github.com/frastlin/bootstrap-react/tree/dev
(if you clone it, the file is:
src/react-wrapped-components/Accordion/index.js)

I messed up the branching, so I need to spend some time to fix that before I can do a PR.

**Comment by accdc** [comment]
Thanks! I'm actually going to be away travelling for the next couple of weeks, so if you can resubmit this as a pull request, then I'll be happy to pull this in as soon as I get back.

**Comment by frastlin** [comment]
Here is the PR:
https://github.com/WhatSock/bootstrap-react/pull/12

Eventually I would like to have a version of the front-page that just uses these wrapped examples. How would you like that to work?

Also, is there a way to figure out, from the callback, what element was clicked on? In the above PR, there is the possibility to give every element it's own callback along with the callback in the group, but currently the group callback is the only one running.

Just using react, I can have an onClick handler run every time an item is clicked, but that's not using the existing tools from AccDC.
